---

- name: Playbook for cisco.nxos.nxos_command
  hosts: sbxnxos
  gather_facts: false
  vars:
    ansible_network_os: cisco.nxos.nxos
    ansible_ssh_port: 22
    ansible_user: admin
    ansible_password: "{{ password }}"
    ansible_become: yes
    ansible_become_method: enable
    ansible_connection: ansible.netcommon.network_cli
    ansible_command_timeout: 60
  vars_prompt:
    - name: password
      prompt: Enter the password

  tasks:
  - name: run show version on remote devices
    cisco.nxos.nxos_command:
      commands:
        - command: show version
          output: json
    register: nxos_version

  - debug:
      var: nxos_version
