---


- name: List NXOS VLANs
  hosts: sbxnxos
  gather_facts: no
  vars:

    ansible_network_os: cisco.nxos.nxos
    ansible_ssh_port: 22
    ansible_user: admin
    ansible_password: "{{ password }}"
    ansible_become: yes
    ansible_become_method: enable
    ansible_connection: ansible.netcommon.network_cli
    ansible_command_timeout: 120
    
  vars_prompt:
    - name: password
      prompt: Enter the password

  tasks:
    - name: Gather all legacy facts
      cisco.nxos.nxos_facts:
        gather_subset: legacy
      register: nxos_facts

    - debug:
        var: nxos_facts['ansible_facts']['ansible_net_vlan_list']
